// Generated by gencpp from file dstar_nav/mapData.msg
// DO NOT EDIT!


#ifndef DSTAR_NAV_MESSAGE_MAPDATA_H
#define DSTAR_NAV_MESSAGE_MAPDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dstar_nav
{
template <class ContainerAllocator>
struct mapData_
{
  typedef mapData_<ContainerAllocator> Type;

  mapData_()
    : map()
    , mapDim()  {
    }
  mapData_(const ContainerAllocator& _alloc)
    : map(_alloc)
    , mapDim(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _map_type;
  _map_type map;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _mapDim_type;
  _mapDim_type mapDim;





  typedef boost::shared_ptr< ::dstar_nav::mapData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dstar_nav::mapData_<ContainerAllocator> const> ConstPtr;

}; // struct mapData_

typedef ::dstar_nav::mapData_<std::allocator<void> > mapData;

typedef boost::shared_ptr< ::dstar_nav::mapData > mapDataPtr;
typedef boost::shared_ptr< ::dstar_nav::mapData const> mapDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dstar_nav::mapData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dstar_nav::mapData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dstar_nav

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'dstar_nav': ['/home/austinnguyen517/Documents/Research/BML/MultiRobot/AN_PathPlanning/dstar_ws/src/dstar_nav/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dstar_nav::mapData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dstar_nav::mapData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dstar_nav::mapData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dstar_nav::mapData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dstar_nav::mapData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dstar_nav::mapData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dstar_nav::mapData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73e74e4094b68133ffe3c8aeb805d77d";
  }

  static const char* value(const ::dstar_nav::mapData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73e74e4094b68133ULL;
  static const uint64_t static_value2 = 0xffe3c8aeb805d77dULL;
};

template<class ContainerAllocator>
struct DataType< ::dstar_nav::mapData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dstar_nav/mapData";
  }

  static const char* value(const ::dstar_nav::mapData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dstar_nav::mapData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] map \n"
"uint8[] mapDim\n"
;
  }

  static const char* value(const ::dstar_nav::mapData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dstar_nav::mapData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map);
      stream.next(m.mapDim);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mapData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dstar_nav::mapData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dstar_nav::mapData_<ContainerAllocator>& v)
  {
    s << indent << "map[]" << std::endl;
    for (size_t i = 0; i < v.map.size(); ++i)
    {
      s << indent << "  map[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.map[i]);
    }
    s << indent << "mapDim[]" << std::endl;
    for (size_t i = 0; i < v.mapDim.size(); ++i)
    {
      s << indent << "  mapDim[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.mapDim[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DSTAR_NAV_MESSAGE_MAPDATA_H
