// Generated by gencpp from file dstar_nav/cliffRequest.msg
// DO NOT EDIT!


#ifndef DSTAR_NAV_MESSAGE_CLIFFREQUEST_H
#define DSTAR_NAV_MESSAGE_CLIFFREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dstar_nav
{
template <class ContainerAllocator>
struct cliffRequest_
{
  typedef cliffRequest_<ContainerAllocator> Type;

  cliffRequest_()
    : pos()  {
    }
  cliffRequest_(const ContainerAllocator& _alloc)
    : pos(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _pos_type;
  _pos_type pos;





  typedef boost::shared_ptr< ::dstar_nav::cliffRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dstar_nav::cliffRequest_<ContainerAllocator> const> ConstPtr;

}; // struct cliffRequest_

typedef ::dstar_nav::cliffRequest_<std::allocator<void> > cliffRequest;

typedef boost::shared_ptr< ::dstar_nav::cliffRequest > cliffRequestPtr;
typedef boost::shared_ptr< ::dstar_nav::cliffRequest const> cliffRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dstar_nav::cliffRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dstar_nav::cliffRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dstar_nav

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'dstar_nav': ['/home/austinnguyen517/Documents/Research/BML/MultiRobot/AN_PathPlanning/dstar_ws/src/dstar_nav/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dstar_nav::cliffRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dstar_nav::cliffRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dstar_nav::cliffRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dstar_nav::cliffRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dstar_nav::cliffRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dstar_nav::cliffRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dstar_nav::cliffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ddbdf76cbefd59cd9a914780fdf2963";
  }

  static const char* value(const ::dstar_nav::cliffRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ddbdf76cbefd59cULL;
  static const uint64_t static_value2 = 0xd9a914780fdf2963ULL;
};

template<class ContainerAllocator>
struct DataType< ::dstar_nav::cliffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dstar_nav/cliffRequest";
  }

  static const char* value(const ::dstar_nav::cliffRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dstar_nav::cliffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] pos\n"
;
  }

  static const char* value(const ::dstar_nav::cliffRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dstar_nav::cliffRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cliffRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dstar_nav::cliffRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dstar_nav::cliffRequest_<ContainerAllocator>& v)
  {
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DSTAR_NAV_MESSAGE_CLIFFREQUEST_H
