// Generated by gencpp from file dstar_nav/edgeResponse.msg
// DO NOT EDIT!


#ifndef DSTAR_NAV_MESSAGE_EDGERESPONSE_H
#define DSTAR_NAV_MESSAGE_EDGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dstar_nav
{
template <class ContainerAllocator>
struct edgeResponse_
{
  typedef edgeResponse_<ContainerAllocator> Type;

  edgeResponse_()
    : weight(0.0)  {
    }
  edgeResponse_(const ContainerAllocator& _alloc)
    : weight(0.0)  {
  (void)_alloc;
    }



   typedef float _weight_type;
  _weight_type weight;





  typedef boost::shared_ptr< ::dstar_nav::edgeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dstar_nav::edgeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct edgeResponse_

typedef ::dstar_nav::edgeResponse_<std::allocator<void> > edgeResponse;

typedef boost::shared_ptr< ::dstar_nav::edgeResponse > edgeResponsePtr;
typedef boost::shared_ptr< ::dstar_nav::edgeResponse const> edgeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dstar_nav::edgeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dstar_nav::edgeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dstar_nav

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dstar_nav': ['/home/austinnguyen517/Documents/Research/BML/MultiRobot/AN_PathPlanning/dstar_ws/src/dstar_nav/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dstar_nav::edgeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dstar_nav::edgeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dstar_nav::edgeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dstar_nav::edgeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dstar_nav::edgeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dstar_nav::edgeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dstar_nav::edgeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ead5cc9b5c68ccc4aabb4fdc1ec2e8db";
  }

  static const char* value(const ::dstar_nav::edgeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xead5cc9b5c68ccc4ULL;
  static const uint64_t static_value2 = 0xaabb4fdc1ec2e8dbULL;
};

template<class ContainerAllocator>
struct DataType< ::dstar_nav::edgeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dstar_nav/edgeResponse";
  }

  static const char* value(const ::dstar_nav::edgeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dstar_nav::edgeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 weight\n"
;
  }

  static const char* value(const ::dstar_nav::edgeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dstar_nav::edgeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.weight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct edgeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dstar_nav::edgeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dstar_nav::edgeResponse_<ContainerAllocator>& v)
  {
    s << indent << "weight: ";
    Printer<float>::stream(s, indent + "  ", v.weight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DSTAR_NAV_MESSAGE_EDGERESPONSE_H
